"""Versioned, evidence-preserving normative knowledge base (M3)."""

from .contracts import (
    M2_HANDOFF_SCHEMA_VERSION,
    M3_SNAPSHOT_SCHEMA_VERSION,
    M2DocumentHandoff,
    M2HandoffService,
    M2IssueSeverity,
    M2QualityIssue,
    M2ReviewStatus,
    document_from_payload,
    m2_handoff_from_payload,
)
from .models import (
    AssetInput,
    BackupArtifact,
    BlockInput,
    Citation,
    DocumentInput,
    DocumentRevision,
    EvidenceConflict,
    EvidenceLocator,
    KnowledgeBaseError,
    KnowledgeBaseRelease,
    KnowledgeBaseSnapshot,
    PageInput,
    PublishedAsset,
    PublishedDocument,
    QualityIssue,
    QualityReport,
    RagAnswer,
    ReviewDecision,
    RevisionStatus,
    SearchHit,
    SearchMode,
    VersionDiff,
)
from .query import KnowledgeBaseQueryService
from .store import KnowledgeBaseStore

__all__ = [
    "M2_HANDOFF_SCHEMA_VERSION",
    "M3_SNAPSHOT_SCHEMA_VERSION",
    "AssetInput",
    "BackupArtifact",
    "BlockInput",
    "Citation",
    "DocumentInput",
    "DocumentRevision",
    "EvidenceConflict",
    "EvidenceLocator",
    "KnowledgeBaseError",
    "KnowledgeBaseQueryService",
    "KnowledgeBaseRelease",
    "KnowledgeBaseSnapshot",
    "KnowledgeBaseStore",
    "M2DocumentHandoff",
    "M2HandoffService",
    "M2IssueSeverity",
    "M2QualityIssue",
    "M2ReviewStatus",
    "PageInput",
    "PublishedAsset",
    "PublishedDocument",
    "QualityIssue",
    "QualityReport",
    "RagAnswer",
    "ReviewDecision",
    "RevisionStatus",
    "SearchHit",
    "SearchMode",
    "VersionDiff",
    "document_from_payload",
    "m2_handoff_from_payload",
]
