"""Application-layer ports for the FMEA evidence handoff."""

from .ports import (
    EvidenceProvider,
    EvidenceRequest,
    EvidenceSnapshot,
    FmeaRepository,
    PropagationEvidenceProvider,
    PropagationRequest,
    ReviewRepository,
    ReviewRunExecutor,
    ReviewSuggestionGenerator,
)
from .review_contracts import (
    EDITABLE_REVIEW_FIELDS,
    ActorContext,
    AuditEvent,
    ConflictItem,
    EvidenceRequestItem,
    FieldFinding,
    FieldReviewEdit,
    FieldReviewState,
    IdempotencyScope,
    MissingEvidenceItem,
    PreparedReviewDecision,
    PreparedSuggestionRun,
    ReviewAction,
    ReviewCandidateBundle,
    ReviewContext,
    ReviewDecisionCommand,
    ReviewDecisionRecord,
    ReviewDecisionResult,
    ReviewEvidenceProjection,
    ReviewEvidenceRef,
    ReviewJudgement,
    ReviewModelManifest,
    ReviewModelRequest,
    ReviewPriority,
    ReviewReasonCode,
    ReviewSourceSnapshot,
    ReviewSuggestion,
    ReviewSuggestionDraft,
    ReviewSuggestionRun,
    RetrievalProvenance,
    StartReviewSuggestionCommand,
    SuggestionRunReservation,
    UnresolvedAcknowledgement,
    canonical_payload_hash,
    idempotency_key_hash,
)
from .review_errors import REVIEW_ERROR_CODES, ReviewError
from .review_projection import build_review_context
from .review_service import ReviewService
from .service_factory import build_review_service
from .structured_candidate_adapter import (
    FmeaAdaptationResult,
    FmeaTemplateProfile,
    StructuredCandidateFmeaAdapter,
)

__all__ = [
    "EDITABLE_REVIEW_FIELDS",
    "ActorContext",
    "AuditEvent",
    "ConflictItem",
    "EvidenceProvider",
    "EvidenceRequest",
    "EvidenceSnapshot",
    "FmeaAdaptationResult",
    "FmeaRepository",
    "FmeaTemplateProfile",
    "EvidenceRequestItem",
    "FieldFinding",
    "FieldReviewEdit",
    "FieldReviewState",
    "IdempotencyScope",
    "MissingEvidenceItem",
    "PreparedReviewDecision",
    "PreparedSuggestionRun",
    "ReviewAction",
    "ReviewCandidateBundle",
    "ReviewContext",
    "ReviewDecisionCommand",
    "ReviewDecisionRecord",
    "ReviewDecisionResult",
    "ReviewError",
    "ReviewEvidenceProjection",
    "ReviewEvidenceRef",
    "ReviewJudgement",
    "ReviewModelManifest",
    "ReviewModelRequest",
    "ReviewPriority",
    "ReviewReasonCode",
    "ReviewRepository",
    "ReviewRunExecutor",
    "ReviewSourceSnapshot",
    "ReviewSuggestion",
    "ReviewSuggestionDraft",
    "ReviewSuggestionGenerator",
    "ReviewSuggestionRun",
    "ReviewService",
    "RetrievalProvenance",
    "StartReviewSuggestionCommand",
    "SuggestionRunReservation",
    "UnresolvedAcknowledgement",
    "REVIEW_ERROR_CODES",
    "canonical_payload_hash",
    "idempotency_key_hash",
    "build_review_context",
    "build_review_service",
    "PropagationEvidenceProvider",
    "PropagationRequest",
    "StructuredCandidateFmeaAdapter",
]
