from __future__ import annotations

import unittest
import re
from pathlib import Path


class FrontendDemoModeContractTests(unittest.TestCase):
    def setUp(self) -> None:
        repo_root = Path(__file__).resolve().parents[2]
        self.root_html = (repo_root / "index.html").read_text(encoding="utf-8")
        self.html = (repo_root / "frontend_app" / "current_console" / "index.html").read_text(encoding="utf-8")

    def test_public_demo_search_uses_browser_local_search_path(self) -> None:
        self.assertRegex(
            self.html,
            re.compile(r"async function runSearch\(\)\s*\{\s*if \(state\.localMode \|\| state\.publicDemo\)"),
        )

    def test_kg_artifacts_only_link_existing_served_files(self) -> None:
        self.assertIn('const KG_ARTIFACT_BASE = "/deliverables/06_四本书KG工具跑通演示/";', self.html)
        self.assertIn('const KG_FILE_ARTIFACT_BASE = "../../docs/project_deliverables/06_四本书KG工具跑通演示/";', self.html)
        self.assertIn('window.location.protocol === "file:"', self.html)
        self.assertIn('{ file: "triples.csv"', self.html)
        self.assertIn('{ file: "run_report.md"', self.html)
        self.assertNotIn('{ file: "schema.json"', self.html)
        self.assertNotIn('{ file: "triples.json"', self.html)
        self.assertNotIn('{ file: "graph.json"', self.html)

    def test_disabling_demo_mode_refreshes_backend_state(self) -> None:
        self.assertIn("state.localMode = FORCE_LOCAL_RUNTIME;", self.html)
        self.assertIn("await refreshAll();", self.html)

    def test_unified_answer_panel_renders_graph_community_source_evidence(self) -> None:
        self.assertIn("function formatUnifiedCitationLine(item)", self.html)
        self.assertIn('kind === "graph_community_source"', self.html)
        self.assertIn("source_evidence", self.html)
        self.assertIn("formatUnifiedCitationLine(item)", self.html)
        self.assertIn("window.formatUnifiedCitationLine = formatUnifiedCitationLine;", self.html)

    def test_root_entrypoint_renders_graph_community_source_evidence(self) -> None:
        self.assertIn("function formatUnifiedCitationLine(item)", self.root_html)
        self.assertIn('kind === "graph_community_source"', self.root_html)
        self.assertIn("source_evidence", self.root_html)
        self.assertIn("formatUnifiedCitationLine(item)", self.root_html)
        self.assertIn("window.formatUnifiedCitationLine = formatUnifiedCitationLine;", self.root_html)

    def test_graph_rag_triage_history_view_exists_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn('id="kgTriageAnalytics"', html)
            self.assertIn('id="kgTriageList"', html)
            self.assertIn('id="btnRefreshKgTriage"', html)
            self.assertIn('id="kgTriageStatusFilter"', html)
            self.assertIn('id="kgTriageReviewFilter"', html)
            self.assertIn('id="kgTriageRouteFilter"', html)
            self.assertIn('id="btnExportKgTriage"', html)
            self.assertIn("async function loadGraphRagTriageAnalytics", html)
            self.assertIn("function renderGraphRagTriageAnalytics", html)
            self.assertIn("function renderGraphRagTriageTrend", html)
            self.assertIn("function renderGraphRagRouteDrilldown", html)
            self.assertIn("async function loadGraphRagTriageHistory", html)
            self.assertIn("async function promoteGraphRagTriageItem", html)
            self.assertIn('requestJson("/api/graphrag/triage/analytics"', html)
            self.assertIn('requestJson("/api/graphrag/triage"', html)
            self.assertIn('/api/graphrag/triage/export', html)
            self.assertIn('/promote', html)
            self.assertIn("source evidence coverage", html)
            self.assertIn("promoted_case_count", html)
            self.assertIn("failure trend", html)
            self.assertIn("route-level drilldown", html)
            self.assertIn("data-triage-note", html)
            self.assertIn("renderGraphRagTriageHistory", html)

    def test_unified_answer_panel_renders_lightrag_diagnostics_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn("function formatLightRagDiagnosticsMarkdown(diagnostics)", html)
            self.assertIn("LightRAG Diagnostics", html)
            self.assertIn("lightrag_diagnostics", html)
            self.assertIn("naive_count", html)
            self.assertIn("local_count", html)
            self.assertIn("global_count", html)
            self.assertIn("active_paths", html)
            self.assertIn("source_type_counts", html)
            self.assertIn("formatLightRagDiagnosticsMarkdown(result?.lightrag_diagnostics)", html)
            self.assertIn("window.formatLightRagDiagnosticsMarkdown = formatLightRagDiagnosticsMarkdown;", html)

    def test_unified_answer_panel_renders_advanced_query_artifacts_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn("function formatAdvancedQueryMarkdown(result)", html)
            self.assertIn("Advanced RAG", html)
            self.assertIn("comparison_table", html)
            self.assertIn("coverage_report", html)
            self.assertIn("advanced_mode", html)
            self.assertIn("planned_queries", html)
            self.assertIn("full_scan", html)
            self.assertIn("global_search", html)
            self.assertIn("formatAdvancedQueryMarkdown(result)", html)
            self.assertIn("window.formatAdvancedQueryMarkdown = formatAdvancedQueryMarkdown;", html)

    def test_wechat_affection_question_forces_full_contact_evidence_contract(self) -> None:
        required = [
            "WECHAT_AFFECTION_QUESTION",
            "全量私聊联系人级暧昧关系分析",
            "不要只基于 top-k chunk",
            "每个一对一私聊联系人",
            "请按联系人逐个分析所有私聊记录",
            "关键证据原文，必须带日期、消息发送方、chunk_id 或 message_id",
            "如果没有原文证据，不允许判断为暧昧",
            "CONTACT_FULL_SCAN",
        ]
        for text in required:
            self.assertIn(text, self.html)

    def test_search_results_render_retrieval_diagnostics_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn("function formatRetrievalDiagnosticsMarkdown(diagnostics)", html)
            self.assertIn("Retrieval Diagnostics", html)
            self.assertIn("retrieval_diagnostics", html)
            self.assertIn("rewritten_queries", html)
            self.assertIn("fusion_mode", html)
            self.assertIn("reranker_error", html)
            self.assertIn("no_answer_reason", html)
            self.assertIn("formatRetrievalDiagnosticsMarkdown(payload.retrieval_diagnostics)", html)

    def test_retrieval_policy_promotion_ui_exists_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn('id="retrievalPolicySettings"', html)
            self.assertIn('id="retrievalPolicyReviewer"', html)
            self.assertIn('id="retrievalPolicyReviewerRole"', html)
            self.assertIn('id="retrievalPolicyReviewNote"', html)
            self.assertIn('id="retrievalPolicyAssignedTo"', html)
            self.assertIn('id="retrievalPolicyDueAt"', html)
            self.assertIn('id="retrievalPolicyNotificationRecipient"', html)
            self.assertIn('id="retrievalPolicyDeliveryMode"', html)
            self.assertIn('id="retrievalPolicyOutboxPath"', html)
            self.assertIn('id="retrievalPolicyWebhookUrl"', html)
            self.assertIn('id="retrievalPolicyWebhookTemplate"', html)
            self.assertIn('id="retrievalPolicyWebhookSigningSecretEnv"', html)
            self.assertIn('id="retrievalPolicyWebhookRoutingKeyEnv"', html)
            self.assertIn('id="retrievalPolicyWebhookAuthHeaderName"', html)
            self.assertIn('id="retrievalPolicyWebhookAuthTokenEnv"', html)
            self.assertIn('id="retrievalPolicyWebhookAuthScheme"', html)
            self.assertIn('id="retrievalPolicySmtpHost"', html)
            self.assertIn('id="retrievalPolicySmtpPort"', html)
            self.assertIn('id="retrievalPolicySmtpFrom"', html)
            self.assertIn('id="retrievalPolicySmtpTo"', html)
            self.assertIn('id="retrievalPolicySmtpSubject"', html)
            self.assertIn('id="retrievalPolicySmtpUseTls"', html)
            self.assertIn('id="retrievalPolicySmtpUsernameEnv"', html)
            self.assertIn('id="retrievalPolicySmtpPasswordEnv"', html)
            self.assertIn('id="retrievalPolicyProposalId"', html)
            self.assertIn('id="retrievalPolicyApprover"', html)
            self.assertIn('id="retrievalPolicyApproverRole"', html)
            self.assertIn('id="retrievalPolicyApprovalNote"', html)
            self.assertIn('id="retrievalPolicyRejectionNote"', html)
            self.assertIn('id="retrievalPolicyRoleSubject"', html)
            self.assertIn('id="retrievalPolicyRoleNames"', html)
            self.assertIn('id="retrievalPolicyRoleCollections"', html)
            self.assertIn('id="retrievalPolicyRoleUpdatedBy"', html)
            self.assertIn('id="retrievalPolicyRecipientSubject"', html)
            self.assertIn('id="retrievalPolicyRecipientEmail"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookUrl"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookTemplate"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookSigningSecretEnv"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookRoutingKeyEnv"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookAuthHeaderName"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookAuthTokenEnv"', html)
            self.assertIn('id="retrievalPolicyRecipientWebhookAuthScheme"', html)
            self.assertIn('id="retrievalPolicyRecipientPreferredDeliveryMode"', html)
            self.assertIn('id="retrievalPolicyRecipientUpdatedBy"', html)
            self.assertIn('id="retrievalPolicyRecipientNote"', html)
            self.assertIn('id="retrievalPolicyDirectoryJson"', html)
            self.assertIn('id="retrievalPolicyDirectoryRoleMappings"', html)
            self.assertIn('id="retrievalPolicyDirectoryRecipientDefaults"', html)
            self.assertIn('id="retrievalPolicyDirectoryUpdatedBy"', html)
            self.assertIn('id="retrievalPolicyDirectoryNote"', html)
            self.assertIn('id="retrievalPolicyIdpEnabled"', html)
            self.assertIn('id="retrievalPolicyIdpIssuer"', html)
            self.assertIn('id="retrievalPolicyIdpAudience"', html)
            self.assertIn('id="retrievalPolicyIdpJwksUrl"', html)
            self.assertIn('id="retrievalPolicyIdpAuthorizationEndpoint"', html)
            self.assertIn('id="retrievalPolicyIdpTokenEndpoint"', html)
            self.assertIn('id="retrievalPolicyIdpClientId"', html)
            self.assertIn('id="retrievalPolicyIdpClientSecretEnv"', html)
            self.assertIn('id="retrievalPolicyIdpRedirectUri"', html)
            self.assertIn('id="retrievalPolicyIdpScopes"', html)
            self.assertIn('id="retrievalPolicyIdpSubjectClaim"', html)
            self.assertIn('id="retrievalPolicyIdpGroupsClaim"', html)
            self.assertIn('id="retrievalPolicyIdpAlgorithms"', html)
            self.assertIn('id="retrievalPolicyIdpUpdatedBy"', html)
            self.assertIn('id="retrievalPolicyIdpNote"', html)
            self.assertIn('id="retrievalPolicyIdpLoginUrl"', html)
            self.assertIn('id="retrievalPolicyIdpAuthCode"', html)
            self.assertIn('id="retrievalPolicyIdpCodeVerifier"', html)
            self.assertIn('id="retrievalPolicySessionId"', html)
            self.assertIn('id="retrievalPolicyBearerToken"', html)
            self.assertIn('id="retrievalPolicyBearerStatus"', html)
            self.assertIn('id="btnUpsertRetrievalPolicyRole"', html)
            self.assertIn('id="btnUpsertRetrievalPolicyRecipient"', html)
            self.assertIn('id="btnLoadRetrievalPolicyRecipients"', html)
            self.assertIn('id="btnSyncRetrievalPolicyDirectory"', html)
            self.assertIn('id="btnSaveRetrievalPolicyIdp"', html)
            self.assertIn('id="btnLoadRetrievalPolicyIdp"', html)
            self.assertIn('id="btnBuildRetrievalPolicyOidcLoginUrl"', html)
            self.assertIn('id="btnOpenRetrievalPolicyOidcLoginUrl"', html)
            self.assertIn('id="btnExchangeRetrievalPolicyOidcCode"', html)
            self.assertIn('id="btnStartRetrievalPolicyOidcSession"', html)
            self.assertIn('id="btnRefreshRetrievalPolicyOidcSession"', html)
            self.assertIn('id="btnLoadRetrievalPolicyOidcSessions"', html)
            self.assertIn('id="btnRevokeRetrievalPolicyOidcSession"', html)
            self.assertIn('id="btnRotateRetrievalPolicyOidcSessionKeys"', html)
            self.assertIn('id="btnLogoutRetrievalPolicyOidcSession"', html)
            self.assertIn('id="btnSaveRetrievalPolicyBearerToken"', html)
            self.assertIn('id="btnClearRetrievalPolicyBearerToken"', html)
            self.assertIn('id="btnProposeRetrievalPolicy"', html)
            self.assertIn('id="btnApproveRetrievalPolicy"', html)
            self.assertIn('id="btnRejectRetrievalPolicy"', html)
            self.assertIn('id="btnPromoteRetrievalPolicy"', html)
            self.assertIn('id="btnRollbackRetrievalPolicy"', html)
            self.assertIn('id="btnLoadRetrievalPolicyHistory"', html)
            self.assertIn('id="btnLoadRetrievalPolicyNotifications"', html)
            self.assertIn('id="btnDispatchRetrievalPolicyNotifications"', html)
            self.assertIn('id="retrievalPolicyDiff"', html)
            self.assertIn("async function proposeRetrievalPolicy", html)
            self.assertIn("async function approveRetrievalPolicy", html)
            self.assertIn("async function rejectRetrievalPolicy", html)
            self.assertIn("async function upsertRetrievalPolicyRole", html)
            self.assertIn("async function upsertRetrievalPolicyRecipient", html)
            self.assertIn("async function loadRetrievalPolicyRecipients", html)
            self.assertIn("async function syncRetrievalPolicyDirectory", html)
            self.assertIn("async function saveRetrievalPolicyIdentityProvider", html)
            self.assertIn("async function loadRetrievalPolicyIdentityProvider", html)
            self.assertIn("async function buildRetrievalPolicyOidcLoginUrl", html)
            self.assertIn("function openRetrievalPolicyOidcLoginUrl", html)
            self.assertIn("async function exchangeRetrievalPolicyOidcCodeForToken", html)
            self.assertIn("async function startRetrievalPolicyOidcSession", html)
            self.assertIn("async function refreshRetrievalPolicyOidcSession", html)
            self.assertIn("async function loadRetrievalPolicyOidcSessions", html)
            self.assertIn("async function revokeRetrievalPolicyOidcSession", html)
            self.assertIn("async function rotateRetrievalPolicyOidcSessionKeys", html)
            self.assertIn("async function logoutRetrievalPolicyOidcSession", html)
            self.assertIn("function withRetrievalPolicyAuthorization", html)
            self.assertIn("function saveRetrievalPolicyBearerToken", html)
            self.assertIn("function clearRetrievalPolicyBearerToken", html)
            self.assertIn("sessionStorage.setItem(RETRIEVAL_POLICY_AUTH_STORAGE_KEY", html)
            self.assertIn('headers.set("Authorization", `Bearer ${token}`)', html)
            self.assertIn("async function promoteRetrievalPolicy", html)
            self.assertIn("async function rollbackRetrievalPolicy", html)
            self.assertIn("async function loadRetrievalPolicyHistory", html)
            self.assertIn("async function loadRetrievalPolicyNotifications", html)
            self.assertIn("async function dispatchRetrievalPolicyNotifications", html)
            self.assertIn('requestJson("/api/retrieval/policies/propose"', html)
            self.assertIn('requestJson("/api/retrieval/policies/approve"', html)
            self.assertIn('requestJson("/api/retrieval/policies/reject"', html)
            self.assertIn('requestJson("/api/retrieval/policies/roles/upsert"', html)
            self.assertIn('requestJson("/api/retrieval/policies/notification-recipients/upsert"', html)
            self.assertIn('requestJson("/api/retrieval/policies/notification-recipients"', html)
            self.assertIn('requestJson("/api/retrieval/policies/directory/sync"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/upsert"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/login-url"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/token"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/session"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/session/refresh"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/sessions"', html)
            self.assertIn('requestJson(`/api/retrieval/policies/identity-provider/sessions/${encodeURIComponent(sessionId)}`', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/sessions/rotate-key"', html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/logout"', html)
            self.assertIn('requestJson("/api/retrieval/policies/promote"', html)

    def test_retrieval_policy_session_admin_view_exists_in_both_entrypoints(self) -> None:
        for html in (self.html, self.root_html):
            self.assertIn('id="retrievalPolicySessionSummary"', html)
            self.assertIn('id="retrievalPolicySessionTable"', html)
            self.assertIn('id="retrievalPolicySessionAudit"', html)
            self.assertIn('id="retrievalPolicySessionKeyStatus"', html)
            self.assertIn('id="btnLoadRetrievalPolicyOidcSessionKeyStatus"', html)
            self.assertIn("function formatRetrievalPolicySessionTime", html)
            self.assertIn("function renderRetrievalPolicyOidcSessions", html)
            self.assertIn("function renderRetrievalPolicySessionAdminAudit", html)
            self.assertIn("function renderRetrievalPolicySessionKeyStatus", html)
            self.assertIn("async function loadRetrievalPolicyOidcSessionKeyStatus", html)
            self.assertIn("data-policy-session-id", html)
            self.assertIn("secret_storage", html)
            self.assertIn("has_refresh_token", html)
            self.assertIn("renderRetrievalPolicyOidcSessions(result)", html)
            self.assertIn("renderRetrievalPolicySessionAdminAudit(result.audit_entry || result)", html)
            self.assertIn("renderRetrievalPolicySessionKeyStatus(result)", html)
            self.assertIn('requestJson("/api/retrieval/policies/identity-provider/sessions/key-status"', html)
            self.assertIn("rotation_due_reasons", html)
            self.assertIn("active_key_id", html)
            self.assertIn("stale_encrypted_session_count", html)
            self.assertIn("identity_provider_session_key_rotate", html)
            self.assertIn("identity_provider_session_revoke", html)
            self.assertIn('requestJson("/api/retrieval/policies/rollback"', html)
            self.assertIn('requestJson(`/api/retrieval/policies/history', html)
            self.assertIn('requestJson(`/api/retrieval/policies/notifications', html)
            self.assertIn('requestJson("/api/retrieval/policies/notifications/dispatch"', html)
            self.assertIn("webhook_url", html)
            self.assertIn("webhook_template", html)
            self.assertIn("webhook_signing_secret_env", html)
            self.assertIn("webhook_routing_key_env", html)
            self.assertIn("webhook_auth_header_name", html)
            self.assertIn("webhook_auth_token_env", html)
            self.assertIn("webhook_auth_scheme", html)
            self.assertIn("role_group_mappings", html)
            self.assertIn("recipient_defaults", html)
            self.assertIn("jwks_url", html)
            self.assertIn("authorization_endpoint", html)
            self.assertIn("token_endpoint", html)
            self.assertIn("client_id", html)
            self.assertIn("client_secret_env", html)
            self.assertIn("redirect_uri", html)
            self.assertIn("scopes", html)
            self.assertIn("subject_claim", html)
            self.assertIn('value="dingtalk_text"', html)
            self.assertIn('value="wecom_text"', html)
            self.assertIn('value="pagerduty_event_v2"', html)
            self.assertIn('value="opsgenie_alert"', html)
            self.assertIn('value="smtp"', html)
            self.assertIn("smtp_host", html)
            self.assertIn("smtp_port", html)
            self.assertIn("smtp_from", html)
            self.assertIn("smtp_to", html)
            self.assertIn("smtp_subject", html)
            self.assertIn("smtp_use_tls", html)
            self.assertIn("smtp_username_env", html)
            self.assertIn("smtp_password_env", html)
            self.assertIn("retrievalPolicyDeliveryMode", html)
            self.assertIn("retrieval_policy", html)
            self.assertIn("retrieval_default_policy", html)


if __name__ == "__main__":
    unittest.main()
